# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 11ff092a3ce0d78afb71dd3574413e00732f2237a67b6f7234524b9a23c18cc0849bc0d52a4e04a287bcf9be2250e0882c3582e91244bd2662a9e4deb27eeb96

test:
  secret_key_base: 05fe372959a5301f6b042141215391b26388e4bf8d9cb415c453501e143ab157c4b02af8a4c9f53b94efc95234544fee2ac17569f2e87f5a22b9860845f36dc5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
